[versions]
cca = "7.3.1"
fpa = "0.6.1"
elmendorf = "0.16.1"

[libraries]
cca-base = { module = "org.ladysnake.cardinal-components-api:cardinal-components-base", version.ref = "cca" }
cca-entity = { module = "org.ladysnake.cardinal-components-api:cardinal-components-entity", version.ref = "cca" }
fpa = { module = "me.lucko:fabric-permissions-api", version.ref = "fpa" }
elmendorf = { module = "org.ladysnake:elmendorf", version.ref = "elmendorf"}
